- alias: Movimiento Cocina o Pasillo
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0000e7c149
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0000fc1838
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: not_home
      - condition: template
        value_template: '{% if states.automation.movimiento_cocina_o_pasillo.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.automation.movimiento_cocina_o_pasillo.attributes.last_triggered)) > 120 }}  {% else %}  true {% endif %}'
  action:
    - service: shell_command.hacervideoentrada

- alias: Movimiento Living
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001103866
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: not_home
      - condition: template
        value_template: '{% if states.automation.movimiento_living.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.automation.movimiento_living.attributes.last_triggered)) > 120 }}  {% else %}  true {% endif %}'
  action:
    - service: shell_command.hacervideobalcon

- alias: Apertura Puerta con video
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001012263
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: not_home
      - condition: template
        value_template: '{% if states.automation.movimiento_cocina_o_pasillo.attributes.last_triggered  %} {{(as_timestamp(now())-as_timestamp(states.automation.movimiento_cocina_o_pasillo.attributes.last_triggered)) > 120 }}  {% else %}  true {% endif %}'
  action:
    - delay: '00:00:01'
    - service: telegram_bot.send_photo
      data:
        target: [ !secret telegram_chat_bel , !secret telegram_chat_gus ]
        url: !secret came_url
        caption: 'Se abrio la puerta Ppal.'
    - delay: '00:04:00'
    - service: telegram_bot.send_document
      data:
        target: [ !secret telegram_chat_bel , !secret telegram_chat_gus ]
        file: '/home/homeassistant/.homeassistant/www/entrada.mp4'


#CUANDO SE ABRE LA VENTANA Y NO ESTAMOS NI BEL NI YO MANDA TELEGRAM CON FOTO.
- alias: Apertura Ventana
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001012257
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.gusdetail
        state: not_home
      - condition: state
        entity_id: group.beldetail
        state: not_home
  action:
    service: notify.telegram_gus
    data_template:
      title: 'Alerta:'
      message: 'Se abrio la ventana.'
      data:
        photo:
          url: !secret camb_url
          caption: 'Se abrio la ventana.'

#CUANDO SE CIERRA LA VENTANA Y NO ESTAMOS NI BEL NI YO MANDA TELEGRAM CON FOTO.
- alias: Cierre Ventana
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001012257
      to: 'off'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.gusdetail
      state: not_home
    - condition: state
      entity_id: group.beldetail
      state: not_home
  action:
    service: notify.telegram_gus
    data_template:
      title: 'Alerta:'
      message: 'Se cerro la ventana.'
      data:
        photo:
          url: !secret camb_url
          caption: 'Se cerro la ventana.'

#- alias: Apertura Puerta
#  trigger:
#    - platform: state
#      entity_id: binary_sensor.door_window_sensor_158d0001012263
#      to: 'on'
#  condition:
#    condition: and
#    conditions:
#    - condition: state
#      entity_id: group.gusdetail
#      state: not_home
#    - condition: state
#      entity_id: group.beldetail
#      state: not_home
#  action:
#    - delay: 0:05
#    - service: notify.telegram_gus
#      data:
#        title: 'Alerta:'
#        message: 'Se abrio la puerta Ppal.'
#        data:
#          photo:
#            url: !secret came_url
#            caption: 'Se abrio la puerta Ppal.'
#    - service: notify.telegram_bel
#      data:
#        title: 'Alerta:'
#        message: 'Se abrio la puerta Ppal.'
#        data:
#          photo:
#            url: !secret came_url
#            caption: 'Se abrio la puerta Ppal.'

- alias: Despertar a Caro
  trigger:
    - platform: time
      at: '06:40:00'
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: '{{ is_state("calendar.feriados_argentina", "off") }}'
#      entity_id: calendar.feriados_argentina
#      state: off
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: script.turn_on
    entity_id: script.despertar_caro

#- alias: Cuando Me voy Camaras
#  trigger:
#    - platform: state
#      entity_id: device_tracker.wmxncdlp_gustavo
#      from: home
#      to: not_home
#  action:
#    service: switch.turn_on
#    entity_id: switch.yawcams

#- alias: Cuando Llego Camaras
#  trigger:
#    - platform: state
#      entity_id: device_tracker.wmxncdlp_gustavo
#      from: not_home
#      to: home
#  action:
#    service: switch.turn_off
#    entity_id: switch.yawcams

- alias: Cuando Llego a casa Musica
  trigger:
    - platform: state
      entity_id: group.gusdetail
      from: not_home
      to: home
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: group.beldetail
      state: not_home
  action:
    - service: media_player.select_source
      data:
        entity_id: media_player.spotify
        source: CENTER
    - service: media_player.media_play
      data:
        entity_id: media_player.spotify

- alias: Cuando Llego al trabajo
  trigger:
    - platform: state
      entity_id: device_tracker.gusplus
      to: trabajo
  action:
    service: media_player.select_source
    data:
      entity_id: media_player.spotify
      source: SAC230999

# Cuando llega Belen
- alias: llego belen
  trigger:
    - platform: state
      entity_id: group.beldetail
      to: 'home'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.gusdetail
      state: not_home
  action:
    service: notify.telegram_gus
    data_template:
      title: 'Alerta:'
      message: 'Belen llego a casa.'

# Cuando llega Gus
- alias: llego gus
  trigger:
    - platform: state
      entity_id: group.gusdetail
      to: 'home'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.beldetail
      state: not_home
  action:
    service: notify.telegram_bel
    data_template:
      title: 'Alerta:'
      message: 'Gustavo llego a casa.'

# Cuando se va Gus
- alias: se fue gus
  trigger:
    - platform: state
      entity_id: group.gusdetail
      to: 'not_home'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.beldetail
      state: not_home
  action:
    service: notify.telegram_bel
    data_template:
      title: 'Alerta:'
      message: 'Gustavo se fue de casa.'

# Cuando se va Belen
- alias: se fue belen
  trigger:
    - platform: state
      entity_id: group.beldetail
      to: 'not_home'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.gusdetail
      state: not_home
  action:
    service: notify.telegram_gus
    data_template:
      title: 'Alerta:'
      message: 'Belen se fue de casa.'

# Cuando llega Paulina
- alias: llego paulina
  trigger:
    - platform: state
      entity_id: device_tracker.paulina
      to: 'home'
  action:
    - service: notify.telegram_bel
      data_template:
        title: 'Alerta:'
        message: 'Paulina llego a casa.'
    - service: notify.telegram_gus
      data_template:
        title: 'Alerta:'
        message: 'Paulina llego a casa.'

# Cuando se va Paulina
- alias: se fue paulina
  trigger:
    - platform: state
      entity_id: device_tracker.paulina
      to: 'not_home'
  action:
    - service: notify.telegram_bel
      data_template:
        title: 'Alerta:'
        message: 'Paulina se fue de casa.'
    - service: notify.telegram_gus
      data_template:
        title: 'Alerta:'
        message: 'Paulina se fue de casa.'

#- alias: prueba_tracker_router
#  trigger:
#    - platform: state
#      entity_id: device_tracker.gustavo
#      to: 'home'
#    - platform: state
#      entity_id: device_tracker.gustavo
#      to: 'not_home'
#  action:
#    - service: notify.telegram_gus
#      data_template:
#        title: 'Alerta:'
#        message: 'gustavo router.'

#- alias: prueba_tracker_gplus
#  trigger:
#    - platform: state
#      entity_id: device_tracker.gusplus
#      to: 'home'
#    - platform: state
#      entity_id: device_tracker.gusplus
#      to: 'not_home'
#  action:
#    - service: notify.telegram_gus
#      data_template:
#        title: 'Alerta:'
#        message: 'gustavo gplus.'